// Shared Lenormand 36-card deck data, used by the main site gallery and the demo tool.
const LENORMAND_CARDS = [
  { num: 1, slug: 'rider', en: 'Rider', zh: '騎士' },
  { num: 2, slug: 'clover', en: 'Clover', zh: '幸運草' },
  { num: 3, slug: 'ship', en: 'Ship', zh: '船' },
  { num: 4, slug: 'house', en: 'House', zh: '房屋' },
  { num: 5, slug: 'tree', en: 'Tree', zh: '樹' },
  { num: 6, slug: 'clouds', en: 'Clouds', zh: '雲' },
  { num: 7, slug: 'snake', en: 'Snake', zh: '蛇' },
  { num: 8, slug: 'coffin', en: 'Coffin', zh: '棺材' },
  { num: 9, slug: 'bouquet', en: 'Bouquet', zh: '花束' },
  { num: 10, slug: 'scythe', en: 'Scythe', zh: '鐮刀' },
  { num: 11, slug: 'whip', en: 'Whip', zh: '鞭子' },
  { num: 12, slug: 'birds', en: 'Birds', zh: '鳥' },
  { num: 13, slug: 'child', en: 'Child', zh: '小孩' },
  { num: 14, slug: 'fox', en: 'Fox', zh: '狐狸' },
  { num: 15, slug: 'bear', en: 'Bear', zh: '熊' },
  { num: 16, slug: 'stars', en: 'Stars', zh: '星星' },
  { num: 17, slug: 'stork', en: 'Stork', zh: '鸛' },
  { num: 18, slug: 'dog', en: 'Dog', zh: '狗' },
  { num: 19, slug: 'tower', en: 'Tower', zh: '塔' },
  { num: 20, slug: 'garden', en: 'Garden', zh: '花園' },
  { num: 21, slug: 'mountain', en: 'Mountain', zh: '山' },
  { num: 22, slug: 'crossroads', en: 'Crossroads', zh: '十字路口' },
  { num: 23, slug: 'mice', en: 'Mice', zh: '老鼠' },
  { num: 24, slug: 'heart', en: 'Heart', zh: '心' },
  { num: 25, slug: 'ring', en: 'Ring', zh: '戒指' },
  { num: 26, slug: 'book', en: 'Book', zh: '書' },
  { num: 27, slug: 'letter', en: 'Letter', zh: '信' },
  { num: 28, slug: 'man', en: 'Man', zh: '男人' },
  { num: 29, slug: 'woman', en: 'Woman', zh: '女人' },
  { num: 30, slug: 'lily', en: 'Lily', zh: '百合' },
  { num: 31, slug: 'sun', en: 'Sun', zh: '太陽' },
  { num: 32, slug: 'moon', en: 'Moon', zh: '月亮' },
  { num: 33, slug: 'key', en: 'Key', zh: '鑰匙' },
  { num: 34, slug: 'fish', en: 'Fish', zh: '魚' },
  { num: 35, slug: 'anchor', en: 'Anchor', zh: '錨' },
  { num: 36, slug: 'cross', en: 'Cross', zh: '十字架' },
];

const LENORMAND_CARDS_BY_NUM = Object.fromEntries(LENORMAND_CARDS.map(c => [c.num, c]));
